name: "vue cli plugin s3 deploy action new"
description: "A Github action for vue-cli-plugin-s3-deploy-new"
author: hungbang
runs:
  using: docker
  image: Dockerfile
branding:
  icon: upload-cloud
  color: green
